/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CnJyNc6kZyX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
export function BannerProd({src}:{src:string}) {
  
  return (
    
    <img
      alt="Banner Image"
      className="w-full object-cover object-center"
      height="500"
      src={src}
      style={{
        aspectRatio: "1920/500",
        objectFit: "fill",
      }}
      width="1920"
    />
  )
}
