/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ofWswi74uOn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Banner(props: { url: string }) {
  return (
    <div className="flex items-center justify-center w-full max-w-md p-6 border border-gray-200 rounded-md gap-6">

    <div className="flex justify-center py-4 md:py-6 lg:py-8">
     <img
  alt="Banner Image"
  className="w-full max-w-[120px] h-[40px] md:h-[60px] lg:h-[80px] object-cover object-center rounded-lg"
  height="40"
  src={props.url}
  style={{
    width: "100%", // Adjusted width
    height: "100%", // Adjusted height
    objectFit: "cover",
  }}
/>

    </div>
    </div>
  )
}
