/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CbBbz7vgYM2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Home() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-950">
      <header className="bg-white dark:bg-gray-900 shadow">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link className="text-2xl font-bold text-gray-900 dark:text-gray-50" href="#">
            Multistore
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Stores
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Categories
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              About
            </Link>
            <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button className="hidden md:inline-flex" size="sm" variant="outline">
              Sign In
            </Button>
            <Button size="sm" variant="primary">
              Sign Up
            </Button>
          </div>
        </div>
      </header>
      <main>
        <section className="py-20 bg-gray-100 dark:bg-gray-950">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div className="space-y-6">
                <h1 className="text-4xl font-bold text-gray-900 dark:text-gray-50">Discover the Best Stores in Town</h1>
                <p className="text-gray-600 dark:text-gray-400 text-lg">
                  Explore a wide range of products and services from local and global businesses.
                </p>
                <div className="flex space-x-4">
                  <Button variant="primary">Explore Stores</Button>
                  <Button variant="outline">Learn More</Button>
                </div>
              </div>
              <div>
                <img
                  alt="Hero Image"
                  className="rounded-lg shadow-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="text-center space-y-6">
              <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-50">Featured Stores</h2>
              <p className="text-gray-600 dark:text-gray-400 text-lg">
                Check out some of the top-rated stores in our marketplace.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 mt-10">
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
                <Link href="#">
                  <img
                    alt="Store 1"
                    className="w-full h-48 object-cover"
                    height={300}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Store 1</h3>
                    <p className="text-gray-600 dark:text-gray-400 mt-2">Clothing and Accessories</p>
                  </div>
                </Link>
              </div>
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
                <Link href="#">
                  <img
                    alt="Store 2"
                    className="w-full h-48 object-cover"
                    height={300}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Store 2</h3>
                    <p className="text-gray-600 dark:text-gray-400 mt-2">Electronics and Gadgets</p>
                  </div>
                </Link>
              </div>
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
                <Link href="#">
                  <img
                    alt="Store 3"
                    className="w-full h-48 object-cover"
                    height={300}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Store 3</h3>
                    <p className="text-gray-600 dark:text-gray-400 mt-2">Home and Decor</p>
                  </div>
                </Link>
              </div>
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg overflow-hidden">
                <Link href="#">
                  <img
                    alt="Store 4"
                    className="w-full h-48 object-cover"
                    height={300}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/300",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-gray-50">Store 4</h3>
                    <p className="text-gray-600 dark:text-gray-400 mt-2">Beauty and Wellness</p>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-20 bg-gray-100 dark:bg-gray-950">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <img
                  alt="Category Image"
                  className="rounded-lg shadow-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-50">Explore by Category</h2>
                <p className="text-gray-600 dark:text-gray-400 text-lg">
                  Browse through our wide range of product categories to find what you're looking for.
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <Link
                    className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-4 flex items-center space-x-4 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    <ShirtIcon className="w-8 h-8 text-primary" />
                    <span className="text-gray-900 dark:text-gray-50 font-medium">Clothing</span>
                  </Link>
                  <Link
                    className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-4 flex items-center space-x-4 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    <CircuitBoardIcon className="w-8 h-8 text-primary" />
                    <span className="text-gray-900 dark:text-gray-50 font-medium">Electronics</span>
                  </Link>
                  <Link
                    className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-4 flex items-center space-x-4 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    <HomeIcon className="w-8 h-8 text-primary" />
                    <span className="text-gray-900 dark:text-gray-50 font-medium">Home</span>
                  </Link>
                  <Link
                    className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-4 flex items-center space-x-4 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    <SmileIcon className="w-8 h-8 text-primary" />
                    <span className="text-gray-900 dark:text-gray-50 font-medium">Beauty</span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="text-center space-y-6">
              <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-50">What Our Customers Say</h2>
              <p className="text-gray-600 dark:text-gray-400 text-lg">
                Hear from our satisfied customers about their experiences.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 mt-10">
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6">
                <div className="flex items-center space-x-4 mb-4">
                  <Avatar>
                    <AvatarImage alt="Customer 1" src="/placeholder-avatar.jpg" />
                    <AvatarFallback>C1</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900 dark:text-gray-50">John Doe</h4>
                    <p className="text-gray-600 dark:text-gray-400">Customer</p>
                  </div>
                </div>
                <p className="text-gray-600 dark:text-gray-400">
                  "I had a great experience shopping at this multistore. The selection was amazing and the customer
                  service was top-notch."
                </p>
              </div>
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6">
                <div className="flex items-center space-x-4 mb-4">
                  <Avatar>
                    <AvatarImage alt="Customer 2" src="/placeholder-avatar.jpg" />
                    <AvatarFallback>C2</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900 dark:text-gray-50">Jane Smith</h4>
                    <p className="text-gray-600 dark:text-gray-400">Customer</p>
                  </div>
                </div>
                <p className="text-gray-600 dark:text-gray-400">
                  "I was able to find everything I needed in one place. The website was easy to navigate and the
                  checkout process was seamless."
                </p>
              </div>
              <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-6">
                <div className="flex items-center space-x-4 mb-4">
                  <Avatar>
                    <AvatarImage alt="Customer 3" src="/placeholder-avatar.jpg" />
                    <AvatarFallback>C3</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900 dark:text-gray-50">Michael Johnson</h4>
                    <p className="text-gray-600 dark:text-gray-400">Customer</p>
                  </div>
                </div>
                <p className="text-gray-600 dark:text-gray-400">
                  "I was impressed by the wide range of products and the competitive prices. I'll definitely be shopping
                  here again."
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-gray-400 py-10">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
            <div>
              <h4 className="text-gray-50 font-bold mb-4">About</h4>
              <ul className="space-y-2">
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Our Story
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Team
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Careers
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="text-gray-50 font-bold mb-4">Stores</h4>
              <ul className="space-y-2">
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Featured Stores
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    All Stores
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Sell on Multistore
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="text-gray-50 font-bold mb-4">Categories</h4>
              <ul className="space-y-2">
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Clothing
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-gray-50 transition-colors" href="#">
                    Electronics
                  </Link>
                </li>
                <li />
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function CircuitBoardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M11 9h4a2 2 0 0 0 2-2V3" />
      <circle cx="9" cy="9" r="2" />
      <path d="M7 21v-4a2 2 0 0 1 2-2h4" />
      <circle cx="15" cy="15" r="2" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function ShirtIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z" />
    </svg>
  )
}


function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}
