/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SteMR8bwq8C
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Logo(props: { url: string }) {
  return (
    <div className="flex items-center justify-center w-full max-w-md p-6 border border-gray-200 rounded-md gap-6">
      <div className="w-16 h-16 flex items-center justify-center p-2 border border-gray-200 rounded-full bg-gray-50 dark:bg-gray-850">
        <img
          alt="Logo"
          className="aspect-[2/1] object-contain overflow-hidden rounded-full border border-gray-200"
          height="30"
          src={props.url} // Corrected: Use props.url instead of url
          width="60"
        />
      </div>
    </div>
  );
}
