/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IrzUZauBZNa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function OrdersAdmin() {
  return (
    <div className="mx-auto px-8 py-16">
      <div className="bg-white rounded-lg shadow-md overflow-hidden">
        <table className="w-full table-auto">
          <thead className="bg-gray-100 text-gray-600 font-medium">
            <tr>
              <th className="px-6 py-4 text-left">Order #</th>
              <th className="px-6 py-4 text-left">Customer</th>
              <th className="px-6 py-4 text-left">Products Ordered</th>
              <th className="px-6 py-4 text-right">Total</th>
              <th className="px-6 py-4 text-left">Status</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            <tr>
              <td className="px-6 py-4 font-medium">
                <Link className="text-blue-500 hover:underline" href="#">
                  #1234
                </Link>
              </td>
              <td className="px-6 py-4">John Doe</td>
              <td className="px-6 py-4">
                <div className="flex flex-col space-y-2">
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 rounded-full bg-gray-200" />
                    <span>Product A</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 rounded-full bg-gray-200" />
                    <span>Product B</span>
                  </div>
                </div>
              </td>
              <td className="px-6 py-4 text-right">$99.99</td>
              <td className="px-6 py-4">
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                  Completed
                </span>
              </td>
              <td className="px-6 py-4 text-right space-x-2">
                <Button className="bg-green-500 text-white hover:bg-green-600" size="sm" variant="outline">
                  Accept
                </Button>
                <Button className="bg-red-500 text-white hover:bg-red-600" size="sm" variant="outline">
                  Reject
                </Button>
              </td>
            </tr>
            <tr>
              <td className="px-6 py-4 font-medium">
                <Link className="text-blue-500 hover:underline" href="#">
                  #1235
                </Link>
              </td>
              <td className="px-6 py-4">Jane Smith</td>
              <td className="px-6 py-4">
                <div className="flex flex-col space-y-2">
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 rounded-full bg-gray-200" />
                    <span>Product C</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 rounded-full bg-gray-200" />
                    <span>Product D</span>
                  </div>
                </div>
              </td>
              <td className="px-6 py-4 text-right">$49.99</td>
              <td className="px-6 py-4">
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                  Pending
                </span>
              </td>
              <td className="px-6 py-4 text-right space-x-2">
                <Button className="bg-green-500 text-white hover:bg-green-600" size="sm" variant="outline">
                  Accept
                </Button>
                <Button className="bg-red-500 text-white hover:bg-red-600" size="sm" variant="outline">
                  Reject
                </Button>
              </td>
            </tr>
            <tr>
              <td className="px-6 py-4 font-medium">
                <Link className="text-blue-500 hover:underline" href="#">
                  #1236
                </Link>
              </td>
              <td className="px-6 py-4">Michael Johnson</td>
              <td className="px-6 py-4">
                <div className="flex flex-col space-y-2">
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 rounded-full bg-gray-200" />
                    <span>Product E</span>
                  </div>
                </div>
              </td>
              <td className="px-6 py-4 text-right">$79.99</td>
              <td className="px-6 py-4">
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
                  Cancelled
                </span>
              </td>
              <td className="px-6 py-4 text-right space-x-2">
                <Button className="bg-green-500 text-white hover:bg-green-600" size="sm" variant="outline">
                  Accept
                </Button>
                <Button className="bg-red-500 text-white hover:bg-red-600" size="sm" variant="outline">
                  Reject
                </Button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  )
}
