/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/POy4Ipzkxze
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import { ShopCart } from "./shop-cart"
import { UserButton } from "@clerk/nextjs"


export function ShopLayout() {
  
    
  
  return (
    <>
      <header className="bg-gray-900  py-4 px-6 md:px-8 flex items-center justify-between">
        <div className="flex  items-center space-x-6">
          <Link className="text-white no-underline text-lg font-bold" href="#">
             Multivendor
          </Link>
          
          <nav className="hidden md:flex space-x-4">
           
            <Link className="text-white no-underline hover:text-gray-300" href="/shop/orders/">
              My orders
            </Link>
            <Link className="text-white no-underline hover:text-gray-300" href="/shop">
              Shops
            </Link>
            
          </nav>
        </div>
        <div className="flex items-center space-x-4">
        
          <Link className="hover:text-gray-300"  href={{
              pathname: '/shop/cart',
              
            }}>
            <ShopCart   />
          </Link>
          <div className="relative " >          <UserButton/>
          </div>
        </div>
      </header>
      <main className="flex-1 py-8 px-6 md:px-8" />
    </>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
