/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QU4C5F2KXm8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useEffect, useState } from "react";
import { Store } from "@/app/lib/types/store";
import { getAllStores } from "@/app/lib/stores";
import { SearchIcon } from "lucide-react";
import { Input } from "../ui/input";
import { ProfileLogo } from "./profile-logo";

export function ShopsPick() {
  const [shops, setShops] = useState<Store[]>([]);
  const fetchShops = async () => {
    try {
      const fetchedShops = await getAllStores();
      if (fetchedShops) {
        setShops(fetchedShops);
      }
    } catch (error) {
      console.error("Error fetching products:", error);
    } 

  };
  useEffect(() => {
    fetchShops();
    console.log('waiting')
  }, []);
  return (
    <main className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-16 lg:py-20">
      <div className="grid gap-6 md:gap-8">
      <div className="flex justify-center items-center ">
  <div className="w-full max-w-screen-lg">
    <div className="relative">
      <div className="absolute left-3 top-1/2 -translate-y-1/2">
        <SearchIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
      </div>
      <Input
        className="w-full rounded-md bg-white px-8 py-2 pl-8 text-sm shadow-sm transition-colors focus:outline-none focus:ring-1 focus:ring-gray-900 dark:bg-gray-800 dark:text-black-50 dark:focus:ring-gray-300"
        placeholder="Search Sellers..."
        type="search"
      />
    </div>
  </div>
</div>

<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
  {shops.slice(0, 20).map((shop, index) => (
    <div key={index} className="text-center relative">
      <Link href={`/shop/products/${shop.id}`}>
        <div className="relative">
          <ProfileLogo
            url={shop.logo}
          />
          
        </div>
        
      </Link>
      <Link href={`/shop/products/${shop.id}`}>
            <Button className="mt-6 bg-black" >{shop.name}</Button> {/* Increased margin-top */}
          </Link>

    </div>
    
  ))}
</div>





      </div>
        
    </main>
  )
}
