/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/POy4Ipzkxze
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import { ShopCart } from "./shop-cart"
import { UserButton } from "@clerk/nextjs"


export function ShopLayout() {
  
    
  
  return (
    <>
      <header className="bg-gray-900  py-4 px-6 md:px-8 flex items-center justify-between">
        <div className="flex  items-center space-x-6">
          <Link className="text-white no-underline text-lg font-bold" href="#">
             Multivendor
          </Link>
          
          <nav className="hidden md:flex space-x-4">
           
            <Link className="text-white no-underline hover:text-gray-300" href="/shop/orders/">
              My orders
            </Link>
            <Link className="text-white no-underline hover:text-gray-300" href="/shop">
              Shops
            </Link>
            
          </nav>
        </div>
        <div className="flex items-center space-x-4">
        
          <Link className="hover:text-gray-300"  href={{
              pathname: '/shop/cart',
              
            }}>
            <ShopCart   />
          </Link>
          <div className="relative " >          <UserButton/>
          </div>
        </div>
      </header>
      <main className="flex-1 py-8 px-6 md:px-8" />
    </>
  )
}

